//* inputDataReducer
export const ADD_NEW_PLAYERS = "ADD_NEW_PLAYERS";
export const CHANGE_PLAYER_BASKET = "CHANGE_PLAYER_BASKET";
export const CALC_BASKET_LENGTH = "CHECK_BASKET_LENGTH";
export const CHANGE_TEAMS_COUNT = "CHANGE_TEAMS_COUNT";
export const CHANGE_MAX_TEAM_PLAYERS = "CHANGE_MAX_TEAM_PLAYERS";
export const CHANGE_MIN_TEAM_PLAYERS = "CHANGE_MIN_TEAM_PLAYERS";
export const TOGGLE_RANDOM = "TOGGLE_RANDOM";
export const TOGGLE_FOCUS = "TOGGLE_FOCUS";
export const UPDATE_SUBS = "UPDATE_SUBS";

//* teamsReducer
export const DIVIDE_TEAMS = "DIVIDE_TEAMS";
export const DIVIDE_BASKET_TEAMS = "DIVIDE_BASKET_TEAMS";
export const CHANGE_TEAM_COLOR = "CHANGE_TEAM_COLOR";
export const PREPARE_PLAYERLIST = "PREPARE_PLAYERLIST";
export const PREPARE_BASKET_LIST = "PREPARE_BASKET_LIST";
export const RESET_TEAM_COLORS = "RESET_TEAM_COLORS";

//* errorReducer
export const CHECK_TEAMS_COUNT = "CHECK_TEAMS_COUNT";
export const CHECK_MAX_TEAM_PLAYERS = "CHECK_MAX_TEAM_PLAYERS";
export const CHECK_MIN_TEAM_PLAYERS = "CHECK_MIN_TEAM_PLAYERS";
export const CHECK_VALIDATION = "CHECK_VALIDATION";
export const CHECK_FOR_REPEATED_PLAYERS = "CHECK_FOR_REPEATED_PLAYERS";
export const SET_REPEATED_ERR_MSG = "SET_REPEATED_ERR_MSG";
export const RESET_REPEATED_ERR_MSG = "RESET_REPEATED_PLAYERS";
export const CHECK_REQUIRED_PLAYERS = "CHECK_REQUIRED_PLAYERS";
export const SET_REQUIRED_ERR_MSG = "SET_REQUIRED_ERR_MSG";
export const RESET_REQUIRED_ERR_MSG = "RESET_REQUIRED";
export const SET_NOT_ENOUGH_ERR_MSG = "SET_NOT_ENOUGH_ERR_MSG";
export const RESET_NOT_ENOUGH_ERR_MSG = "RESET_NOT_ENOUGH_ERR_MSG";
export const CHECK_BASKET_LENGTH_ERR = "CHECK_BASKET_LENGTH_ERR";
